# Project specific configuration settings - REFERENCE
# Purely considering boosting architecture

# GLOBAL SETTINGS

project_name: 'power-forecasting'

# LOGGING CONFIGURATION

logging_settings:
  level: 'INFO'
  format: '%(asctime)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'

# PATHS / FILENAMES

paths:
  data_dir: 'data/'
  era5_zip_dir: 'data/'
  era5_extract_dir: 'data/era5_extracted/'
  power_flow_path: 'data/ukpn-primary-transformer-power-flow-historic-half-hourly.csv'
  sites_path: 'data/grid-and-primary-sites.csv'
  skt_files_path: 'data/ukpn_data/skt_*.nc'
  model_output_dir: 'models'
  xgboost_model_filename: 'xgboost_power_forecaster.pkl'
  lstm_model_filename: 'lstm_power_forecaster.h5'
  cnn_model_filename: 'cnn_power_forecaster.h5'
  plot_output_dir: 'output_plots'
  processed_features_path: 'data/processed_X.csv'
  processed_target_path: 'data/processed_y.csv'
  processed_master_path: 'data/processed_master_df.csv'

# DATA INGESTION PARAMETERS

data_ingestion_params:
  target_transformer_ids:
    - 'aldreth_primary_11kv_t1'
    - 'bourn_primary_11kv_t1'
    - 'bungay_primary_11kv_t1'
    - 'chartham_11kv_t1'
    - 'danbury_primary_11kv_t1'
    - 'hitcham_primary_11kv_t1'
    - 'sandy_primary_11kv_t1'
    - 'sundridge_11kv_t1'
    - 'thaxted_local_11kv_t1'
    - 'worstead_primary_11kv_t1'
    - 'austin_street_primary_11kv_t1'
    - 'basildon_local_primary_11kv_t1'
    - 'hendon_way_primary_11kv_t1'
    - 'kingsbury_primary_11kv_t1'
    - 'madingley_rd_primary_11kv_t1'
    - 'marshalswick_primary_11kv_t1'
    - 'ruxley_11kv_t1'
    - 'peachman_way_primary_11kv_t1'
    - 'stopsley_11kv_t1'
    - 'whapload_rd_primary_11kv_t1'
  analysis_start_date: '2021-01-01'
  analysis_end_date: '2024-12-31'
  power_csv_cols:
    timestamp: 'timestamp'
    active_power_mw: 'power'
    tx_id: 'tx_id'
  era5_vars:
    - 'tcc'
    - 'ssrd'
    - 't2m'
    - 'skt'
  weather_vars_map:
    tcc: 'cloud_cover'
    ssrd: 'solar_radiation'
    t2m: 'air_temperature'
    skt: 'skin_temperature'
  era5_zip_filenames:
    - '1ad607f0fce80941fdc5bc4c97df5242.zip'
    - '2f58f379803541c69b1d740bd5e64ea4.zip'
    - '3df5d74f8b870ce52425007b18feccae.zip'
    - '5a009d2445c81124187bda7081a2a2e0.zip'
    - '5feb33a8896e7836a14585ff0b781d0c.zip'
    - '7e393de69db80f9fa352944156922d44.zip'
    - '9a9f107d6898d694d91227eae1afdc47.zip'
    - '9b2406b6aa7854353fcabf76f5df9d4.zip'
    - '30c5913b0b7d460536a18a0a722e7dce.zip'
    - '32bc63c218dec9ba5e3446ca7c2e08e.zip'
    - '70a491bb8f44e7a05b56423806bfa152.zip'
    - '170ac59b1ee6b516fa77daee6c19e367.zip'
    - '410b3610b43296796015f89063dae376.zip'
    - '533b0e70a841b045f29f1ee1dd58c608.zip'
    - '9953cc1b89cbadc63fdf5574b3f3f86a.zip'
    - '23406af64990516f6f82078a6f08a372.zip'
    - '44253784ff620229a9adbcaf1e8e7a0e.zip'
    - '766253913f1fae9599d2637d803aad4d.zip'
    - 'b1e4a8d1891c601e3f90d8311c4c2229.zip'
    - 'b7e53a108e50d6315a89da0e3bf833e7.zip'
    - 'b19e9b8428429a62780c2c37e8a74bea.zip'
    - 'c5b5904167cfa1356d6e2e4ff3be4db7.zip'
    - 'd4ff02e04064e092855efdbb3131f3fd.zip'
    - 'f2d43f6d5d5b2de76bb34e19091d482e.zip'
    - '6503c171b40075241422bbb47619588a.zip'
    - 'e8cdc6c4ee6a1370ab48970bd09e81db.zip'

# FEATURE ENGINEERING PARAMETERS

feature_params:
  target_column: 'power'
  tcc_var_name: 'tcc'
  base_weather_lags: [1, 3, 6, 12, 24]
  base_weather_roll_windows: [3, 6, 12, 24]
  power_interaction_lags: [1, 2, 3, 6, 12, 24, 48, 168]
  power_interaction_roll_windows: [3, 6, 12, 24, 48, 168]
  interaction_weather_lags: [1, 6, 24]

# MODEL - XGBOOST

model_params:
  split_dates:
    train_end: '2022-12-31 23:00:00'
    val_start: '2023-01-01 00:00:00'
    val_end: '2023-12-31 23:00:00'
    test_start: '2024-01-01 00:00:00'
  estimator_params:
    objective: 'reg:squarederror'
    random_state: 42
    n_jobs: -1
    tree_method: 'hist'
  monotonic_constraints:
    't2m_lag_1h': -1
    'ssrd_lag_1h': -1
    'tcc_lag_1h': 1
  hyperparameter_search:
    n_iterations: 50
    n_cv_splits: 4
    scoring: 'neg_root_mean_squared_error'
    verbose: 2
    random_state: 42
    param_distributions:
      n_estimators: "randint(100, 1001)"
      learning_rate: "uniform(0.005, 0.095)"
      max_depth: "randint(3, 11)"
      subsample: "uniform(0.6, 0.4)"
      colsample_bytree: "uniform(0.6, 0.4)"
      min_child_weight: "randint(1, 8)"
      gamma: "loguniform(0.001, 0.4)"
      reg_alpha: "loguniform(1e-5, 0.5)"
      reg_lambda: "loguniform(0.01, 1.0)"

# COMMON NEURAL NETWORK PARAMETERS

common_nn_params:
  look_back_window: 24
  optimizer:
    learning_rate: 0.0001
    clipnorm: 1.0
  loss_function: 'mse'
  early_stopping_patience: 15
  reduce_lr_patience: 7
  reduce_lr_factor: 0.5
  min_learning_rate: 0.000005
  epochs: 200
  batch_size: 64
  validation_split: 0.2

# MODEL - LSTM

lstm_params:
  lstm_units_1: 64
  lstm_units_2: 32
  activation: 'tanh'
  dropout_rate: 0.3

# MODEL - CNN

cnn_params:
  filters_1: 32
  filters_2: 16
  kernel_size: 3
  pool_size: 2
  dense_units: 25
  activation: 'relu'
  dropout_rate: 0.3

# PLOTTING

plotting:
  save_plots: true
  plot_start_date: '2024-01-02'
  plot_end_date: '2024-01-08'

# SCENARIO GENERATION PARAMS

scenario_analysis_params:
  simulation_start_date: '2023-07-01 00:00:00'
  simulation_end_date: '2023-07-07 23:00:00'
  look_back_buffer_hours: 170
  midday_start_hour: 11
  midday_end_hour: 14
  ssrd_high_percentile: 99
  tcc_low_percentile: 1
  temp_high_percentile: 95
  temp_low_percentile: 5

historical_analogy_params:
  low_sun_tcc_threshold: 0.95
  low_sun_ssrd_threshold: 1000
  low_sun_t2m_k_threshold: 276.15
  high_sun_tcc_threshold: 0.1
  high_sun_ssrd_threshold: 2000000
  high_sun_t2m_k_threshold: 283.15
  target_site_id: 'marshalswick_primary_11kv_t1'
  comparison_duration_hours: 168
  weather_column_prefixes: ['tcc', 'ssrd', 't2m', 'skt']
  smoothing_window: 3
  random_seed: 42
  midday_start_hour: 11
  midday_end_hour: 14
